version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  study-database:
    container_name: study-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: heeyoungha/study-database
    environment:
      - MYSQL_DATABASE=study-version
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
