spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sopt.cj6c6qseak8m.ap-northeast-2.rds.amazonaws.com:3306/sopt
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1093062512798-2od4q9a5p467gptto7a4o56uvkfsmm91.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://letsadam.link/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경. openid가 scope에 있으면 Open Id Provider로 인식하기 때문
              - profile
              - email

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema.internal.SchemaCreatorImpl: TRACE
    org.springframework.security: DEBUG

cafe:
  recommendation:
    base:
      url: http://3.36.241.20/dir # 고정 ip 할당 받은 후 변경 예정