"""add summary to bookclub_entry

Revision ID: 02da17af1169
Revises: 7cf263a82eeb
Create Date: 2025-07-19 18:56:53.350038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02da17af1169'
down_revision: Union[str, Sequence[str], None] = '7cf263a82eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookclub_entry', sa.Column('summary', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookclub_entry', 'summary')
    # ### end Alembic commands ###
