"""add summary to diary

Revision ID: 19c7d285a99c
Revises: 02da17af1169
Create Date: 2025-07-19 23:39:46.711601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c7d285a99c'
down_revision: Union[str, Sequence[str], None] = '02da17af1169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('summary', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary', 'summary')
    # ### end Alembic commands ###
