"""create bookclub_entry table

Revision ID: 7a4042d06c36
Revises: 9505a17db848
Create Date: 2025-07-19 18:07:35.558916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a4042d06c36'
down_revision: Union[str, Sequence[str], None] = '9505a17db848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('diary', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('diary', 'created_at')
    op.drop_column('diary', 'sentiment')
    op.drop_column('diary', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('diary', sa.Column('sentiment', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=False))
    op.add_column('diary', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('diary', 'content')
    op.drop_column('diary', 'date')
    # ### end Alembic commands ###
