"""create bookclub_entry table

Revision ID: 7cf263a82eeb
Revises: 7a4042d06c36
Create Date: 2025-07-19 18:13:56.304010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf263a82eeb'
down_revision: Union[str, Sequence[str], None] = '7a4042d06c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookclub_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('book_title', sa.String(length=255), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('recommended_projects', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookclub_entry_id'), 'bookclub_entry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookclub_entry_id'), table_name='bookclub_entry')
    op.drop_table('bookclub_entry')
    # ### end Alembic commands ###
