"""add sentiment to diary2

Revision ID: ec0e2ad42d42
Revises: ca6b836408b6
Create Date: 2025-07-19 23:43:51.134475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec0e2ad42d42'
down_revision: Union[str, Sequence[str], None] = 'ca6b836408b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookclub_entry', 'sentiment')
    op.add_column('diary', sa.Column('sentiment', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary', 'sentiment')
    op.add_column('bookclub_entry', sa.Column('sentiment', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=True))
    # ### end Alembic commands ###
