# default
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}  # default
    group:
      local:  # local, common profile? ???? ?? ?????? ??
        - common
      prod:   # prod, common profile? ???? ?? ?????? ??
        - common

---
spring:
  config:
    activate:
      on-profile: common   # application-common.yml ? ??? ??

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}



---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/study-version
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # 스프링부트 3.x는 이렇게 설정해야 + 명시적 Dialect 설정
        ddl-auto: create #create???? ?? ?? ???? ?? ????? create?? ??? ???? ???? ? ????
    properties:
      hibernate:
        #show_sql: true
        format_sql: true


cafe:
  recommendation:
    base:
      url: http://localhost:8080/dir/
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/study-version
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # 스프링부트 3.x는 이렇게 설정해야 + 명시적 Dialect 설정
    ddl-auto: create #create???? ?? ?? ???? ?? ????? create?? ??? ???? ???? ? ????
    show-sql: true

pharmacy:
  recommendation:
    base:
      url: http://35.209.134.113/dir # 고정 ip 할당 받은 후 변경 예정

