version: 1
formatters:
  default:
    format: "%(asctime)s %(levelname)s %(name)s %(message)s"
handlers:
  file:
    class: logging.FileHandler
    formatter: default
    filename: logs/app.log
  console:
    class: logging.StreamHandler
    formatter: default
loggers:
  uvicorn:
    handlers: [file, console]
    level: INFO
  uvicorn.error:
    handlers: [file, console]
    level: ERROR
  uvicorn.access:
    handlers: [file, console]
    level: INFO
root:
  handlers: [file, console]
  level: INFO 